//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Material
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHANNEL_MASTER_TAXATION
    {
        public string CHANNEL_CODE { get; set; }
        public string TAN { get; set; }
        public string PAN { get; set; }
        public string ECC_NUMBER { get; set; }
        public string RANGE { get; set; }
        public string RANGE_ADDR { get; set; }
        public string DIVISION { get; set; }
        public string COMMISSIONERATE { get; set; }
        public string COMM_ADDR { get; set; }
        public string VAT_TIN { get; set; }
        public string SERVICE_TAX_NO { get; set; }
        public string SSI_REG_NO { get; set; }
        public string ESIC_NO { get; set; }
        public string CIN_NO { get; set; }
    }
}
