//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Material
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHANNEL_MASTER_FIDATA
    {
        public string CHANNEL_CODE { get; set; }
        public string ACC_INFO_GL_AC_NO { get; set; }
        public string ACC_INFO_SORT_KEY { get; set; }
        public string TDS_WHT_TYPE { get; set; }
        public string TDS_TYPE_OF_RECIPIENT { get; set; }
        public string TDS_EXEMPTION_REASON { get; set; }
    }
}
