//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Material
{
    using System;
    using System.Collections.Generic;
    
    public partial class DISTRICT_MST
    {
        public int SLNO { get; set; }
        public string DISTRICT_NAME { get; set; }
        public string STATE_CODE { get; set; }
        public string ISACTIVE { get; set; }
        public Nullable<int> CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_ON { get; set; }
        public Nullable<int> RELEASE_BY { get; set; }
        public Nullable<System.DateTime> RELEASE_ON { get; set; }
    }
}
