//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Material
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVOICE_MASTER_1820001300
    {
        public int SLNO { get; set; }
        public string CHANNEL_CODE { get; set; }
        public string SUPPLIER_GSTIN { get; set; }
        public string SUPPLIER_CIN { get; set; }
        public string INVOICE_NUMBER { get; set; }
        public string INVOICE_DATE { get; set; }
        public string PO_NUM { get; set; }
        public string HSN_SAC_No { get; set; }
        public string ITEM_CODE { get; set; }
        public string QUANTITY { get; set; }
        public string RATE { get; set; }
        public string AMOUNT { get; set; }
        public string CGST { get; set; }
        public string CGST_AMT { get; set; }
        public string IGST { get; set; }
        public string IGST_AMT { get; set; }
        public string SGST { get; set; }
        public string SGST_AMT { get; set; }
        public string CESS { get; set; }
        public string TOTAL_VALUE_INC { get; set; }
        public string TOTAL_VALUE_EXC { get; set; }
        public Nullable<int> CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_ON { get; set; }
        public string STATUS { get; set; }
        public Nullable<int> ACC_REJ_BY { get; set; }
        public Nullable<System.DateTime> ACC_REJ_ON { get; set; }
        public string ACC_REJ_REMARKS { get; set; }
        public string MODEL { get; set; }
        public string MFG_DATE { get; set; }
        public string BATCHCODE { get; set; }
        public string CALC_VALUE_INC { get; set; }
        public string CALC_VALUE_EXC { get; set; }
        public string SCHEDULE_NO { get; set; }
        public string DEL_DATE { get; set; }
        public string CONTRACT_NO { get; set; }
        public string POSITION_NO { get; set; }
        public string CGST_PER { get; set; }
        public string SGST_PER { get; set; }
        public string IGST_PER { get; set; }
    }
}
