//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Material
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification_Mst
    {
        public int SL_No { get; set; }
        public string Notification_Txt { get; set; }
        public string Channel_Code { get; set; }
        public string Type_ { get; set; }
        public string Status { get; set; }
        public Nullable<int> USERTYPE { get; set; }
    }
}
