//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Material
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLANT_MASTER14062018
    {
        public int SLNO { get; set; }
        public string PLANT_CODE { get; set; }
        public string PLANT_NAME { get; set; }
    }
}
