//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Material
{
    using System;
    using System.Collections.Generic;
    
    public partial class PO_INVOICE_CONFIG_MASTER
    {
        public int SLNO { get; set; }
        public string FIELD_NAME { get; set; }
        public string FIELD_DESC { get; set; }
        public string MANDATORY { get; set; }
        public string ISACTIVE { get; set; }
        public string ISDATEFORMAT { get; set; }
        public string VALIDATION_TYPE { get; set; }
        public string INPUT_TYPE { get; set; }
    }
}
