//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Material
{
    using System;
    using System.Collections.Generic;
    
    public partial class PO_SCHEDULE_DTLS14062018
    {
        public int SLNO { get; set; }
        public Nullable<int> REFNO { get; set; }
        public string SUPPLIER_CODE { get; set; }
        public string PLANT_CODE { get; set; }
        public string MAT_CODE { get; set; }
        public string CONTRACT_NO { get; set; }
        public string POSITION_NO { get; set; }
        public string SCHEDULE_NO { get; set; }
        public string QUANTITY { get; set; }
        public string DEL_DATE { get; set; }
        public string STATUS { get; set; }
        public string ACC_REJ_REMARKS { get; set; }
        public string Is_BillGenerated { get; set; }
    }
}
