//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Material
{
    using System;
    using System.Collections.Generic;
    
    public partial class PO_SCHEDULE_MST
    {
        public int SLNO { get; set; }
        public string SCHEDULE { get; set; }
        public string SCHEDULE_NO { get; set; }
        public string SUPPLIER_CODE { get; set; }
        public string SUPPLIER_NAME { get; set; }
        public string CHANNEL_CODE { get; set; }
        public string STATUS { get; set; }
        public Nullable<int> CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_ON { get; set; }
        public string CREATED_REMARKS { get; set; }
        public Nullable<int> ACC_REJ_BY { get; set; }
        public Nullable<System.DateTime> ACC_REJ_ON { get; set; }
        public string ACC_REJ_REMARKS { get; set; }
        public string DEL_DATE { get; set; }
    }
}
