//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Material
{
    using System;
    using System.Collections.Generic;
    
    public partial class RFQ_MASTER
    {
        public int SLNO { get; set; }
        public string SUP_CODE { get; set; }
        public string BUYER_FILENAME { get; set; }
        public string SUP_FILENAME { get; set; }
        public string STATUS { get; set; }
        public string DeclineRemarks { get; set; }
        public string CREATED_ON { get; set; }
        public string UPDATED_ON { get; set; }
        public string UPLOAD_REMARKS { get; set; }
        public string DATE_VALID { get; set; }
    }
}
