//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Material
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_SUBACTIVITY_LINK_MAPPING
    {
        public int SNO { get; set; }
        public string LINK_CODE { get; set; }
        public string SUBACTIVITY_CODE { get; set; }
        public Nullable<System.DateTime> STARTDATE { get; set; }
        public Nullable<System.DateTime> ENDDATE { get; set; }
        public Nullable<int> CREATED_BY { get; set; }
        public Nullable<int> RELEASE_BY { get; set; }
    }
}
