//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Material
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_MASTER
    {
        public int SNO { get; set; }
        public string NAME { get; set; }
        public string EMPCODE { get; set; }
        public string MOBILE_NO { get; set; }
        public string EMAILID { get; set; }
        public string ADDRESS1 { get; set; }
        public string ADDRESS2 { get; set; }
        public string CONTACTNO { get; set; }
        public string STATE { get; set; }
        public Nullable<int> CITY { get; set; }
        public string PIN { get; set; }
        public string USERNAME { get; set; }
        public string PASSWORD { get; set; }
        public string STATUS { get; set; }
        public Nullable<System.DateTime> CREATEDON_DT { get; set; }
        public Nullable<System.DateTime> LASTLOGIN_DT { get; set; }
        public Nullable<System.DateTime> PASSWORDEXP_DT { get; set; }
        public string USERTYPE { get; set; }
        public string DEPARTMENT { get; set; }
        public Nullable<int> CREATED_BY { get; set; }
        public Nullable<int> RELEASE_BY { get; set; }
    }
}
