//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Material
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_MASTER_MAPPING
    {
        public int SNO { get; set; }
        public int REFNO { get; set; }
        public string CHANNEL_CODE { get; set; }
        public string ISACTIVE { get; set; }
        public Nullable<System.DateTime> ASSIGN_DT { get; set; }
        public Nullable<System.DateTime> RELEASE_DT { get; set; }
        public Nullable<int> CREATED_BY { get; set; }
        public Nullable<int> RELEASE_BY { get; set; }
    }
}
