//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurchaseOrder
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VendorPortalEntities : DbContext
    {
        public VendorPortalEntities()
            : base("name=VendorPortalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUserRole> AspNetUserRoles { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<INVOICE> INVOICEs { get; set; }
        public virtual DbSet<INVOICE_DETAILS> INVOICE_DETAILS { get; set; }
        public virtual DbSet<Plant_Master> Plant_Master { get; set; }
        public virtual DbSet<PO> POes { get; set; }
        public virtual DbSet<PO_DETAILS> PO_DETAILS { get; set; }
        public virtual DbSet<PublicHoliday> PublicHolidays { get; set; }
        public virtual DbSet<Schedule> Schedules { get; set; }
        public virtual DbSet<STATE_MST> STATE_MST { get; set; }
        public virtual DbSet<SUPPLIER_MASTER> SUPPLIER_MASTER { get; set; }
        public virtual DbSet<tblApprovedPackingStandard> tblApprovedPackingStandards { get; set; }
        public virtual DbSet<tblCertificate> tblCertificates { get; set; }
        public virtual DbSet<tblCity> tblCities { get; set; }
        public virtual DbSet<tblECN> tblECNs { get; set; }
        public virtual DbSet<tblFileMetaData> tblFileMetaDatas { get; set; }
        public virtual DbSet<tblFOC> tblFOCs { get; set; }
        public virtual DbSet<tblGRN> tblGRNs { get; set; }
        public virtual DbSet<tblInvoiceRejecttion> tblInvoiceRejecttions { get; set; }
        public virtual DbSet<tblLineStopage> tblLineStopages { get; set; }
        public virtual DbSet<tblMaterial> tblMaterials { get; set; }
        public virtual DbSet<tblNotification> tblNotifications { get; set; }
        public virtual DbSet<tblPPM> tblPPMs { get; set; }
        public virtual DbSet<tblRating> tblRatings { get; set; }
        public virtual DbSet<tblStock> tblStocks { get; set; }
        public virtual DbSet<tblUnit> tblUnits { get; set; }
        public virtual DbSet<tblVendorInfo> tblVendorInfoes { get; set; }
        public virtual DbSet<tblVendorQue> tblVendorQues { get; set; }
        public virtual DbSet<tblWarrantyPartsRejected> tblWarrantyPartsRejecteds { get; set; }
        public virtual DbSet<VENDOR_ASSOC> VENDOR_ASSOC { get; set; }
        public virtual DbSet<BASIC_MST> BASIC_MST { get; set; }
        public virtual DbSet<PO_MASTER> PO_MASTER { get; set; }
        public virtual DbSet<tblUserRole> tblUserRoles { get; set; }
    }
}
