//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurchaseOrder
{
    using System;
    using System.Collections.Generic;
    
    public partial class PO
    {
        public long ID { get; set; }
        public string PO_NUM { get; set; }
        public Nullable<System.DateTime> PO_DATE { get; set; }
        public string SUPP_CODE { get; set; }
        public Nullable<int> STATUS { get; set; }
        public string ACC_REJ_Remark { get; set; }
        public Nullable<System.DateTime> ACC_REJ_DateTime { get; set; }
    }
}
