//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurchaseOrder
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFileMetaData
    {
        public long Id { get; set; }
        public string FileName { get; set; }
        public string FileType { get; set; }
        public string Location { get; set; }
        public string DocumentType { get; set; }
        public System.DateTime UploadDate { get; set; }
        public Nullable<System.DateTime> LastModified { get; set; }
        public Nullable<System.DateTime> ValidTill { get; set; }
        public Nullable<long> SupplierId { get; set; }
        public string SupplierName { get; set; }
        public Nullable<int> MaterialId { get; set; }
        public string MaterialCode { get; set; }
        public bool Status { get; set; }
        public int Active { get; set; }
        public string UploadedBy { get; set; }
        public string Tags { get; set; }
        public string Field1 { get; set; }
        public string Field2 { get; set; }
        public string Field3 { get; set; }
        public string Field4 { get; set; }
        public string Field5 { get; set; }
    }
}
