//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurchaseOrder
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFOC
    {
        public long Id { get; set; }
        public string VendorCode { get; set; }
        public string VendorName { get; set; }
        public string MaterialCode { get; set; }
        public string MaterialName { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<decimal> OpeningBalance { get; set; }
        public Nullable<decimal> IssueQty { get; set; }
        public Nullable<decimal> ReceivedQty { get; set; }
        public Nullable<decimal> BSLClosingBalance { get; set; }
        public Nullable<decimal> SuppStockInHand { get; set; }
        public Nullable<decimal> SuppRejtedQty { get; set; }
        public Nullable<decimal> SuppClosingBalance { get; set; }
        public Nullable<decimal> Difference { get; set; }
        public Nullable<System.DateTime> LastModified { get; set; }
        public bool Status { get; set; }
        public int Active { get; set; }
        public string UploadedBy { get; set; }
    }
}
