//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurchaseOrder
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLineStopage
    {
        public long Id { get; set; }
        public string Plant { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string LineNumber { get; set; }
        public string SuppCode { get; set; }
        public string SuppName { get; set; }
        public string MatCode { get; set; }
        public string MatDes { get; set; }
        public string Instance { get; set; }
        public string DurationFrom { get; set; }
        public string DurationTo { get; set; }
        public string StopTime { get; set; }
        public string ReasonNo { get; set; }
        public string ReasonDescription { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> UploadDate { get; set; }
        public string UploadedBy { get; set; }
        public Nullable<System.DateTime> ValidTill { get; set; }
        public int Active { get; set; }
    }
}
