//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurchaseOrder
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRating
    {
        public long Id { get; set; }
        public string RatingMonth { get; set; }
        public string FinancialYear { get; set; }
        public string CummRank { get; set; }
        public string SuppCode { get; set; }
        public string SuppName { get; set; }
        public Nullable<decimal> MDeliveryRating { get; set; }
        public Nullable<decimal> MQualityRating { get; set; }
        public Nullable<decimal> MOverallRating { get; set; }
        public Nullable<decimal> CDeliveryRating { get; set; }
        public Nullable<decimal> CQualityRating { get; set; }
        public Nullable<decimal> COverallRating { get; set; }
        public string Grade { get; set; }
        public Nullable<System.DateTime> UploadDate { get; set; }
        public string UploadedBy { get; set; }
        public Nullable<System.DateTime> ValidTill { get; set; }
        public int Active { get; set; }
    }
}
