//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurchaseOrder
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblWarrantyPartsRejected
    {
        public long Id { get; set; }
        public System.DateTime Date { get; set; }
        public string SuppCode { get; set; }
        public string SuppName { get; set; }
        public string WarrantyNumber { get; set; }
        public string Model { get; set; }
        public string PartCode { get; set; }
        public string WarrantyDescription { get; set; }
        public Nullable<decimal> WarrantyCost { get; set; }
        public Nullable<System.DateTime> UploadDate { get; set; }
        public string UploadedBy { get; set; }
        public Nullable<System.DateTime> ValidTill { get; set; }
        public int Active { get; set; }
    }
}
