//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schedules
{
    using System;
    using System.Collections.Generic;
    
    public partial class PO_DETAILS
    {
        public long ID { get; set; }
        public string PO_NUM { get; set; }
        public string PLANT_CODE { get; set; }
        public string MaterialCode { get; set; }
        public string HSN_SAC { get; set; }
        public string GL_ACC { get; set; }
        public Nullable<decimal> QUANTITY { get; set; }
        public string UOM { get; set; }
        public Nullable<decimal> UNIT_RATE { get; set; }
        public Nullable<decimal> DISCOUNT { get; set; }
        public Nullable<decimal> NET_AMOUNT { get; set; }
        public Nullable<decimal> FREIGHT { get; set; }
        public Nullable<decimal> PF { get; set; }
        public Nullable<decimal> CGST { get; set; }
        public Nullable<decimal> SGST { get; set; }
        public Nullable<decimal> IGST { get; set; }
        public Nullable<decimal> CESS { get; set; }
        public Nullable<decimal> TOTAL_VALUE_INC { get; set; }
        public Nullable<decimal> TOTAL_VALUE_EXC { get; set; }
        public Nullable<System.DateTime> CREATEDON { get; set; }
        public Nullable<int> STATUS { get; set; }
        public string ACC_REJ_BY { get; set; }
        public Nullable<System.DateTime> ACC_REJ_ON { get; set; }
        public string ACC_REJ_REMARKS { get; set; }
    }
}
