//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schedules
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblApprovedPackingStandard
    {
        public long Id { get; set; }
        public string SupplierName { get; set; }
        public string MaterialCode { get; set; }
        public string FileName { get; set; }
        public System.DateTime UploadDate { get; set; }
        public bool Status { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public string ModifyBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    }
}
