//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schedules
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCertificate
    {
        public int Id { get; set; }
        public string IATFTS { get; set; }
        public string IATFTSLOC { get; set; }
        public string ISO { get; set; }
        public string ISOLOC { get; set; }
        public string OHSAS { get; set; }
        public string OHSASLOC { get; set; }
        public string Environment { get; set; }
        public string EnvironmentLOC { get; set; }
        public string Other1 { get; set; }
        public string Other1LOC { get; set; }
        public string Other2 { get; set; }
        public string Other2LOC { get; set; }
        public string Other3 { get; set; }
        public string Other3LOC { get; set; }
        public Nullable<System.DateTime> UploadDate { get; set; }
        public Nullable<System.DateTime> LastModified { get; set; }
        public Nullable<System.DateTime> ValidTill { get; set; }
        public Nullable<long> SupplierId { get; set; }
        public string SupplierName { get; set; }
        public Nullable<bool> Status { get; set; }
        public string UploadedBy { get; set; }
        public string Tags { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> Field1 { get; set; }
        public Nullable<System.DateTime> Field2 { get; set; }
        public Nullable<System.DateTime> Field3 { get; set; }
        public Nullable<System.DateTime> Field4 { get; set; }
        public Nullable<System.DateTime> Field5 { get; set; }
        public Nullable<System.DateTime> Field6 { get; set; }
        public Nullable<System.DateTime> Field7 { get; set; }
        public Nullable<int> Active { get; set; }
    }
}
