//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schedules
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGRN
    {
        public long ID { get; set; }
        public string SupplierCode { get; set; }
        public string SupplierNAme { get; set; }
        public string MaterialCode { get; set; }
        public string MaterialDescription { get; set; }
        public string PlantCode { get; set; }
        public string PlantName { get; set; }
        public string PONO { get; set; }
        public string MRNNo { get; set; }
        public string InvoiceNo { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public Nullable<System.DateTime> PstngDate { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public string UOM { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
