//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schedules
{
    using System;
    using System.Collections.Generic;
    
    public partial class VENDOR_ASSOC
    {
        public long ID { get; set; }
        public string VENDOR_CODE { get; set; }
        public string USER_CODE { get; set; }
        public Nullable<int> IsActive { get; set; }
    }
}
