//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VendorPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BASIC_MST
    {
        public string CODE { get; set; }
        public string DESCRIPTION { get; set; }
        public string IDENTIFIER { get; set; }
        public string ISACTIVE { get; set; }
        public Nullable<int> CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_ON { get; set; }
        public Nullable<int> RELEASE_BY { get; set; }
        public Nullable<System.DateTime> RELEASE_ON { get; set; }
        public int ID { get; set; }
    }
}
