//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VendorPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVOICE
    {
        public long ID { get; set; }
        public string INVOICE_NUMBER { get; set; }
        public string SUPP_CODE { get; set; }
        public string SUPPLIER_GSTIN { get; set; }
        public string SUPPLIER_CIN { get; set; }
        public Nullable<System.DateTime> INVOICE_DATE { get; set; }
        public Nullable<long> POID { get; set; }
        public string HSN_SAC_NO { get; set; }
        public Nullable<int> CREATEDBY { get; set; }
        public Nullable<System.DateTime> CREATEDON { get; set; }
        public Nullable<int> IsActive { get; set; }
    }
}
