//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VendorPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVOICE_DETAILS
    {
        public long ID { get; set; }
        public Nullable<long> INV_ID { get; set; }
        public string MAT_CODE { get; set; }
        public Nullable<decimal> QTY { get; set; }
        public Nullable<decimal> RATE { get; set; }
        public Nullable<decimal> AMOUNT { get; set; }
        public Nullable<decimal> CGST { get; set; }
        public Nullable<decimal> CGST_AMT { get; set; }
        public Nullable<decimal> IGST { get; set; }
        public Nullable<decimal> IGST_AMT { get; set; }
        public Nullable<decimal> SGST { get; set; }
        public Nullable<decimal> SGST_IMT { get; set; }
        public Nullable<decimal> CESS { get; set; }
        public Nullable<decimal> TOTAL_VAL_INC { get; set; }
        public Nullable<decimal> TOTAL_VAL_EXC { get; set; }
        public Nullable<int> CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_ON { get; set; }
        public Nullable<int> STATUS { get; set; }
        public string MODEL { get; set; }
        public Nullable<System.DateTime> MFG_DATE { get; set; }
        public string BATCHCODE { get; set; }
        public Nullable<decimal> CALC_VALUE_EXC { get; set; }
        public Nullable<decimal> CALC_VALUE_INC { get; set; }
        public string SCHEDULE_NO { get; set; }
        public Nullable<System.DateTime> DEL_DATE { get; set; }
        public string CONTRACT_NO { get; set; }
        public string POSITION_NO { get; set; }
        public Nullable<decimal> CGST_PER { get; set; }
        public Nullable<decimal> SGST_PER { get; set; }
        public Nullable<decimal> IGST_PER { get; set; }
        public Nullable<long> SCH_ID { get; set; }
    }
}
