//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VendorPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUPPLIER_MASTER
    {
        public long Id { get; set; }
        public string SUPP_CODE { get; set; }
        public string SUPP_TYPE { get; set; }
        public string PURCHASING_RELATED { get; set; }
        public string SUPP_NAME { get; set; }
        public string ADDRESS1 { get; set; }
        public string ADDRESS2 { get; set; }
        public string ADDRESS3 { get; set; }
        public string CITY { get; set; }
        public string PIN { get; set; }
        public string DISTRICT { get; set; }
        public string STATE { get; set; }
        public string COUNTRY { get; set; }
        public string COUNTRY_EXTRA { get; set; }
        public string CIN { get; set; }
        public string VATREG_NO1 { get; set; }
        public string VATREG_NO2 { get; set; }
        public string TIN2_1 { get; set; }
        public string TIN2_2 { get; set; }
        public string GSTIN { get; set; }
        public string COMM_TEL1 { get; set; }
        public string COMM_TEL2 { get; set; }
        public string COMM_TEL3 { get; set; }
        public string COMM_FAX { get; set; }
        public string COMM_EMAIL { get; set; }
        public string PAYMENT_TERM { get; set; }
        public string PAYMENT_METHOD { get; set; }
        public string BANK_NAME { get; set; }
        public string BANK_ADDRESS1 { get; set; }
        public string BANK_ADDRESS2 { get; set; }
        public string BANK_ACC_NO { get; set; }
        public string BANK_SWIFT_CODE1 { get; set; }
        public string BANK_SWIFT_CODE2 { get; set; }
        public string BANK_SWIFT_CODE3 { get; set; }
        public string BANK_CURRENCY1 { get; set; }
        public string BANK_CURRENCY2 { get; set; }
        public string PUR_ORD_CUR { get; set; }
        public string PUR_ORD_INCO1 { get; set; }
        public string PUR_ORD_INCO2 { get; set; }
        public string PUR_ORD_SCH_GROUP_VENDOR { get; set; }
        public string PUR_ORD_CONTACT_PERSON { get; set; }
        public string PUR_ORD_CONTACT_NO { get; set; }
        public string PUR_ORD_GR_BASED_IV { get; set; }
        public string PUR_ORD_ERS_VENDOR { get; set; }
        public string ADDITIONAL_INFO1 { get; set; }
        public string ADDITIONAL_INFO2 { get; set; }
        public string ADDITIONAL_INFO3 { get; set; }
        public string ADDITIONAL_INFO4 { get; set; }
        public string REQUESTER_ID { get; set; }
        public Nullable<System.DateTime> REQUEST_DATE { get; set; }
        public string REQUEST_DEP { get; set; }
        public string ISACTIVE { get; set; }
        public string EMAIL_ID { get; set; }
        public string CONTACT_NO { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedBy { get; set; }
    }
}
