//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VendorPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStock
    {
        public long ID { get; set; }
        public string PONO { get; set; }
        public string SUPPLIERCODE { get; set; }
        public string SUPPLIERNAME { get; set; }
        public string MATERIALCODE { get; set; }
        public string MATERIALDESCRIPTION { get; set; }
        public string RAWMATERIAL { get; set; }
        public string UOM { get; set; }
        public string WIP { get; set; }
        public string WIPUOM { get; set; }
        public string FINISHGOODS { get; set; }
        public string FINISHGOODSUOM { get; set; }
        public string REMARK { get; set; }
        public System.DateTime PODATE { get; set; }
        public string CREATEDBY { get; set; }
        public System.DateTime CREATEDON { get; set; }
    }
}
